# Q1

In [2]:
import numpy as np

a = np.array([0,1,2,3,4,5,6,7,8])

b = np.reshape(a,(3,3))

print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Q2

In [3]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
for i in range(1,len(arr)+1,2):
    arr[i] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# Q3

In [78]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
arr1 = []
arr2 = []
for i in range(10):
    if(x[i]>y[i]):
        arr1.append(i)
    elif(x[i]==y[i]):
        arr2.append(i)
print(np.array(arr1))
print(np.array(arr2))

[1 2 4 5 6 7 8 9]
[0]


# Q4

In [5]:
arr =  np.arange(100).reshape(5,-1)
print(arr[:,:4])

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


# Additional 1

In [6]:
a = np.random.randint(30,40,size=10)
print(a)

[35 36 32 39 31 30 33 31 35 31]


# Additional 2

In [8]:
A= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
B = np.array([[7, 8, 10] ,[4, 5, 6], [1, 2, 3]])

Part 1

In [59]:
C = A-B
print(C)
print("\n")
E = A+B
print(D)

[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]


[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]


Part 2

In [60]:
sum_A = np.sum(A)
sum_B = np.sum(B, axis=0)
sum_C = np.sum(C, axis=1)


In [61]:
print(sum_A)
print(sum_B)
print(sum_C)

46
[12 15 19]
[-19   0  19]


Part 3

In [63]:
D = np.dot(A, B)
print(D)

[[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]


Part 4

In [66]:
F = np.sort(C, axis=None).reshape(C.shape)
print(F)

[[-7 -6 -6]
 [ 0  0  0]
 [ 6  6  7]]


Part 5

In [70]:
E = E.T
print(E)

[[ 8  8  8]
 [10 10 10]
 [13 12 13]]
